matrix:
  include:

    # Go

    - language: go
      before_install:
        - cd go

    # JavaScript

    - language: node_js
      node_js: "node"
      before_install:
        - cd javascript

    # PHP

    - language: php
      before_install:
        - cd php

    # Python

    - language: python
      python:
        - "3.6"
      before_install:
        - cd python
      script:
        - python huifier_test.py

    # Ruby

    - language: ruby
      before_install:
        - cd ruby
      script:
        - ruby tc_huifier.rb

    # Rust

    - language: rust
      before_install:
        - cd rust

    # TypeScript

    - language: node_js
      node_js: "node"
      before_install:
        - cd typescript
